[settings]
storymode = true
storymodemethod = 1
storymode_max_length = 1000
max_allowed_com = 30
allow_comment = false
allow_title = true
allow_title_picture = true
allow_nsfw = false
auto_selection = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
fps = 30
vwidth = 1920
bitrate = "6M"
resolution_w = "1080"
resolution_h = "1920"
len = 20
crop = true
no_repeate = true
manul_data = false
fast_render = true
use_temp = false

[fonts]
normal_font = "Roboto-Regular.ttf"
title_font = "Roboto-Bold.ttf"
title_font_size = 40
normal_font_size = 30
single_word_font_size = 150

[image]
bg_is_transparent = false
bg_trans = 200
dark_bg_color = [ 0, 0, 0,]
dark_text_color = [ 215, 218, 220,]
light_bg_color = [ 255, 255, 255,]
light_text_color = [ 0, 0, 0,]
max_im_w_story = 600

[pereference]
manual_text_correct = false

[settings.background]
background_choice = ""

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "br_004"
python_voice = "1"
py_voice_num = "2"
edge_voice = "en-US-SteffanNeural"
edge_speed = 10

[reddit.creds]
client_id = "mwQ91OhCt3kVjenwiQwJqQ"
client_secret = "NPbnsee8CY2Tsz93EuJ6leysBI5edg"
username = "Murdock_NC"
password = "RvljSqK2/'BuDtD;"
2fa = false

[reddit.thread]
random = false
subreddit = "PergunteReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
